Repository datalad/datalad-deprecated, pull requests merged in 2022-10, with the labels that each got.

#67 Update GitHub Actions action versions
  .github/workflows/docbuild.yml
  .github/workflows/release.yml
  .github/workflows/test_crippledfs.yml
  .github/workflows/test_js.yml
Labels: internal

#70 "Fix" one failing test and improve their "infrastructure"
  datalad_deprecated/conftest.py
  datalad_deprecated/tests/test_publish.py
  setup.cfg
  tox.ini
Labels: release, tests

#68 Configure Dependabot to update GitHub Actions action versions
  .github/dependabot.yml
Labels: internal

#71 Crossport core-located metadata bug-fixes
  datalad_deprecated/metadata/aggregate.py
  datalad_deprecated/metadata/metadata.py
  datalad_deprecated/metadata/search.py
  datalad_deprecated/metadata/tests/test_search.py
  datalad_deprecated/metadata/utils.py
Labels: patch, release

#73 BF: Adjust imports for metadata move
  README.md
  datalad_deprecated/metadata/extractors/tests/test_datacite_xml.py
  datalad_deprecated/metadata/metadata.py
  datalad_deprecated/metadata/tests/test_aggregation.py
  datalad_deprecated/metadata/tests/test_base.py
  datalad_deprecated/metadata/tests/test_extract_metadata.py
  datalad_deprecated/metadata/tests/test_search.py
Labels: patch, release

#78 Add deprecated metadata config procedure from datalad core
  README.md
  datalad_deprecated/conftest.py
  datalad_deprecated/resources/procedures/cfg_metadatatypes.py
Labels: patch, release
